# The default build for wasp-os. Modify to customize your own build.
# At least one watch face must be specified. Quick ring apps will be added in order.

[[app]]
file = 'apps/stopwatch.py'
quick_ring = true

[[app]]
file = 'apps/heart.py'
quick_ring = true

[[app]]
file = 'apps/alarm.py'
auto_load = true

[[app]]
file = 'apps/timer.py'
auto_load = true

[[app]]
file = 'apps/calculator.py'

[[app]]
file = 'apps/disa_b_l_e.py'

[[app]] # If only one watch face is included this app can be removed
file = 'apps/faces.py'
auto_load = true
no_except = true

[[watchface]]
file = 'watch_faces/clock.py'

[[watchface]] # Requires ClockApp to also be installed
file = 'watch_faces/week_clock.py'
default = true

[[watchface]]
file = 'watch_faces/chrono.py'